# Generated by Django 4.2 on 2023-04-18 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=250)),
                ('tournaments', models.ManyToManyField(to='tournament.tournament')),
            ],
        ),
    ]
