# Generated by Django 4.2 on 2023-08-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_remove_player_user"),
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameresult",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.player"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player1",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player2",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_won",
                to="players.player",
            ),
        ),
    ]
