# Generated by Django 4.2 on 2023-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tournament_type', models.CharField(choices=[('K.O.', 'Knockout'), ('group', 'Group')], max_length=200)),
                ('players_number', models.SmallIntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='tournaments', to='players.player')),
            ],
        ),
    ]
