# Generated by Django 4.2 on 2023-08-15 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerTournamentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Single Elimination"),
                            ("league", "League"),
                        ],
                        max_length=20,
                    ),
                ),
                ("players_count", models.PositiveIntegerField()),
                ("points_for_win", models.PositiveIntegerField(default=3)),
                ("points_for_draw", models.PositiveIntegerField(default=1)),
                ("points_for_loss", models.PositiveIntegerField(default=0)),
                ("games", models.ManyToManyField(to="game.game")),
                (
                    "players",
                    models.ManyToManyField(
                        through="tournament.PlayerTournamentScore",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playertournamentscore",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
    ]
