# Generated by Django 4.2 on 2023-08-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_remove_player_user"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playertournamentscore",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.player"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(
                through="tournament.PlayerTournamentScore", to="players.player"
            ),
        ),
    ]
